name: Test

on:
  push:
    branches:
      - *
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "test"

